version: '3.3'

networks:
  ntpgsql:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24

services:
  pgsql:
    image: postgres:latest
    restart: unless-stopped
    container_name: postgresql
    volumes:
      - psdb-volume:/var/lib/postgresql/data
    networks:
      ntpgsql:
        ipv4_address: 172.21.0.2
    ports:
      - target: 5432
        published: 5433
        protocol: tcp
        mode: host
    environment:
      - POSTGRES_PASSWORD=123_Stella
  pgadmin:
    image: dpage/pgadmin4:4.15
    restart: unless-stopped
    container_name: pgadmin4
    volumes:
      - type: bind
        source: ./dockervol
        target: /var/lib/pgadmin/storage/admin
    networks:
      ntpgsql:
        ipv4_address: 172.21.0.3
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin
      - PGADMIN_DEFAULT_PASSWORD=123_Stella


volumes:
  psdb-volume:

