version: '3.3'

networks:
  ntmongo:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/24

services:
  mongo:
    image: mongo
    restart: unless-stopped
    container_name: mongodb
    volumes:
      - data-volume:/data/db
    networks:
      ntmongo:
        ipv4_address: 172.22.0.2
    ports:
      - 27017-27019:27017-27019
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    container_name: mongodb-express
    networks:
      ntmongo:
        ipv4_address: 172.22.0.3
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

volumes:
  data-volume:
