# ==============================================================
# = Articoli Web Service - Versione Base
# ==============================================================

server:
  port: 5051

spring:
  application:
     name: ProductsWebService
# ==============================================================
# = DBMS PostgreSQL Parameters
# ==============================================================
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:h2:file:~/test;DB_CLOSE_ON_EXIT=FALSE
    username: test
    password: test
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true

guestuser:
  url: http://localhost:8019/api/user/search/userid/
  user: ReadUser
  password: BimBumBam_2018

# ==============================================================
# = Parametri Sicurezza JWT
# ==============================================================
sicurezza:
  uri: /auth
  refresh: /refresh
  header: Authorization
  prefix: Bearer
  expiration: 86400
  secret: 123_Stella
