# ==============================================================
# = GestUser - Servizio Gestione Utenti 
# ==============================================================

server:
  port: 8019
spring:
  application:
    name: GestUser

# ==============================================================
# = MONGODB Parameters
# ==============================================================

spring.mongodb.embedded.storage.database-dir: ./user-web-service/embeddedMongoDB
spring.mongodb.embedded.storage.oplog-size: 0
